apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: curso-gitops
  labels:
    app: mysql
spec:
  # ClusterIP (default) — solo accesible desde dentro del cluster
  # La app Go se conecta usando DB_HOST=mysql-svc
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
